# Generated by Django 5.1.2 on 2024-10-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('press', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('keyword', models.TextField()),
                ('image', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
