# Generated by Django 5.0.7 on 2024-11-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=1)),
                ("last_searched", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-count"],
            },
        ),
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("query", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "group_by",
                    models.CharField(
                        choices=[("1day", "일간"), ("1week", "주간"), ("1month", "월간")],
                        default="1day",
                        max_length=10,
                    ),
                ),
                ("title_summary", models.CharField(max_length=100)),
                ("content_summary", models.TextField()),
                ("news_count", models.IntegerField()),
                (
                    "representative_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="daily_summaries/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "query", "group_by"],
                        name="web_dailysu_date_42be6d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=100)),
                ("press", models.CharField(max_length=20)),
                ("author", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("keyword", models.TextField()),
                ("image", models.TextField()),
                ("link", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "press"], name="web_news_date_232a64_idx"
                    ),
                    models.Index(
                        fields=["date", "-press"], name="web_news_date_b66c73_idx"
                    ),
                    models.Index(
                        fields=["keyword"], name="web_news_keyword_b43295_idx"
                    ),
                    models.Index(
                        fields=["date", "keyword"], name="web_news_date_67db04_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=200)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "group_by",
                    models.CharField(
                        choices=[("1day", "일간"), ("1week", "주간"), ("1month", "월간")],
                        default="1day",
                        max_length=10,
                    ),
                ),
                ("background", models.TextField()),
                ("core_content", models.TextField()),
                ("conclusion", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["keyword", "date", "group_by"],
                        name="web_newssum_keyword_0522f4_idx",
                    )
                ],
                "unique_together": {("keyword", "date", "group_by")},
            },
        ),
    ]
