# Generated by Django 5.0.7 on 2024-11-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=1)),
                ("last_searched", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-count"],
            },
        ),
        migrations.DeleteModel(
            name="NewsAnalysis",
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["date", "press"], name="web_news_date_232a64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["date", "-press"], name="web_news_date_b66c73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(fields=["keyword"], name="web_news_keyword_b43295_idx"),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["date", "keyword"], name="web_news_date_67db04_idx"
            ),
        ),
    ]
