# Generated by Django 5.0.7 on 2024-11-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_searchhistory_delete_newsanalysis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=200)),
                ("date", models.DateField(blank=True, null=True)),
                ("background", models.TextField()),
                ("core_content", models.TextField()),
                ("conclusion", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["keyword", "date"],
                        name="web_newssum_keyword_dd9f1f_idx",
                    )
                ],
                "unique_together": {("keyword", "date")},
            },
        ),
    ]
