# Generated by Django 5.0.7 on 2024-11-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_newssummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('query', models.CharField(blank=True, max_length=200, null=True)),
                ('group_by', models.CharField(choices=[('1day', '일간'), ('1week', '주간'), ('1month', '월간')], default='1day', max_length=10)),
                ('title_summary', models.CharField(max_length=100)),
                ('content_summary', models.TextField()),
                ('news_count', models.IntegerField()),
                ('representative_image', models.ImageField(blank=True, null=True, upload_to='daily_summaries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='newssummary',
            name='web_newssum_keyword_dd9f1f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='newssummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='newssummary',
            name='group_by',
            field=models.CharField(choices=[('1day', '일간'), ('1week', '주간'), ('1month', '월간')], default='1day', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='newssummary',
            unique_together={('keyword', 'date', 'group_by')},
        ),
        migrations.AddIndex(
            model_name='newssummary',
            index=models.Index(fields=['keyword', 'date', 'group_by'], name='web_newssum_keyword_0522f4_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['date', 'query', 'group_by'], name='web_dailysu_date_42be6d_idx'),
        ),
    ]
